version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vakar
      POSTGRES_PASSWORD: vakar1234
      POSTGRES_DB: ToDoList
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: